name: Update Application Repository

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clear local repo
        run: |
          rm -rf .git
          rm -rf .github

      - name: Clone Application repository
        run: |
          cd ..
          git clone https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/BlueChatDevelop/Application.git app-repo
          cd app-repo
          git checkout main

      - name: Copy frontend folder to Application repository
        run: |
          cd ..
          rm -rf ./app-repo/Backend
          cp -r ./Frontend ./app-repo/
          cd app-repo
          git add .
          git commit -m "Update Application repository with the latest changes from frontend" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/BlueChatDevelop/Application.git main
